---
- name: Install pre-requisite packages
  become: true
  ansible.builtin.package:
    name: 
      - nfs-utils
    state: latest
  when: (external_immich_upload_enabled | bool) or (external_lib_enabled | bool)