---
- name: "Ensure Immich data directories exist"
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  loop:
    - "{{ immich_upload_location }}"
    - "{{ immich_db_data_location }}"
    - "{{ immich_redis_data_location }}"
    - "{{ immich_generated_data_location }}"
    - "{{ immich_json_logs_location }}"