---
- name: "Ensure core Immich data directories exist"
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ immich_container_uid }}"
    group: "{{ immich_container_gid }}"
    mode: '0755'
  loop:
    - "{{ immich_upload_location }}"
    - "{{ immich_db_data_location }}"
    - "{{ immich_redis_data_location }}"
    - "{{ immich_generated_data_location }}"
    - "{{ immich_json_logs_location }}"

- name: |
    Ensure external library mount point directory exists (if not already mounted).
    - This task creates the directory specified by 'external_lib_dst'.
    - It only runs if 'external_lib_enabled' is true AND 'external_lib_dst' is not already an active mount point.
    - This prevents errors when trying to chown/chmod an already mounted (potentially read-only) filesystem.
  become: true
  ansible.builtin.file:
    path: "{{ external_lib_dst }}"
    state: directory
    owner: "{{ immich_container_uid }}"
    group: "{{ immich_container_gid }}"
    mode: '0755'
  when:
    - external_lib_enabled | bool
    - external_lib_dst not in (ansible_mounts | map(attribute='mount') | list)

- name: Mount External Library as Read-Only
  become: true
  ansible.posix.mount:
    src: "{{ external_lib_src }}:{{ external_lib_src_export_path }}"
    path: "{{ external_lib_dst }}"
    fstype: "nfs"
    opts: "ro,sync,hard,intr" 
    state: "mounted"
  when: external_lib_enabled | bool
