---
- name: "Create Immich Podman network"
  become_user: "{{ ansible_user }}"
  containers.podman.podman_network:
    name: "{{ immich_network_name }}"
    state: present

- name: "Define Podman volumes to be created"
  ansible.builtin.set_fact:
    podman_volumes_to_create:
      - { name: "pgdata" }
      - { name: "redisdata" }
      - { name: "immich-generated" }
      - { name: "immich-model-cache" } # For ML model caching
      - { name: "immich-logs" } # For JSON log files (bind mount defined in defaults)
      - { name: "immich-upload", condition: "not (external_immich_upload_enabled | bool)" }

- name: "Create Podman volumes"
  become_user: "{{ ansible_user }}"
  containers.podman.podman_volume:
    name: "{{ item.name }}"
    state: present
  loop: "{{ podman_volumes_to_create }}"
  loop_control:
    label: "{{ item.name }}"
  when: item.condition | default(true)