---
- name: Converge
  hosts: all
  gather_facts: true
  roles:
    - role: apigban.immich_podman

  tasks:
    - name: Check uname
      ansible.builtin.raw: uname -a
      register: result
      changed_when: false

    - name: Print some info
      ansible.builtin.assert:
        that: result.stdout | regex_search("^Linux")
